# Generated by Django 5.0.7 on 2024-07-10 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "note_url",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note_text", models.CharField(max_length=200)),
                ("note_visit", models.BigIntegerField()),
                ("expiry_date", models.DateTimeField()),
            ],
        ),
    ]
