# Generated by Django 5.0.7 on 2024-07-14 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretnote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="visits",
            field=models.IntegerField(default=0),
        ),
    ]
