# Generated by Django 5.0.7 on 2024-07-14 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secretnote", "0002_note_pub_date_note_visits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="note_visit",
            new_name="note_remvisit",
        ),
        migrations.RemoveField(
            model_name="note",
            name="visits",
        ),
    ]
